name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout target
        uses: actions/checkout@v6
        with:
          repository: henrypp/memreduct
          ref: refs/tags/v.3.5.2
          path: memreduct

      - name: Fetch deps
        run: |
          git submodule update --init --recursive

      - name: Restore dependency packages
        run: |
          nuget restore

      - name: Setup msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 14.29
          sdk: 10.0.19041.0

      - name: Build
        working-directory: memreduct
        run: msbuild memreduct.sln
          /p:PlatformToolset=v142 `
          /p:WindowsTargetPlatformVersion=10.0.19041.0 `
          /p:Platform=x64 `
          /p:Configuration=Release `
          /p:WholeProgramOptimization=true `
          /p:Optimization=MinSpace `
          /p:FunctionLevelLinking=true

      - name: Archive Binary
        uses: actions/upload-artifact@v5
        with:
          name: memreduct
          path: |
            x64/Release/*.dll
            x64/Release/*.exe
